Models for topic and sentiment analysis
uchicago-capp-30320/CivicLens pull request #114
Opened 2024-05-06 16:35 UTC by jgibson517

@abejburton opening this draft for your awareness. topic and sentiment analysis functions are good to go, will start integrating into the ml pipeline // writing tests

2024-05-06 16:49 UTC, abejburton commented
I'm making progress on the pipeline, will try to get something simple running today then push a draft pr so we can then make sure our two branches are integrating well

2024-05-08 00:06 UTC, jgibson517 commented
@abejburton I pushed a commit with a draft for a`Comments` dataclass if you want to take a look

2024-05-09 19:46 UTC, abejburton requested changes
Want to discuss timestamps and make sure we aren't creating conflicts with the pipeline code that will be merged into main first. Other than that, looks great and ready to go

2024-05-09 21:17 UTC, jgibson517 commented on civiclens/nlp/topics.py
> +    created_at: datetime = datetime.today()
sounds good! I'm going to remove this class and integrate any other features onto your `DocComments` class

2024-05-09 22:54 UTC, jgibson517 commented
@abejburton made a few tweaks but this is now go to go, lets merge this and your pipeline draft and then i'll open a PR to integrate//complete the pipeline

2024-05-10 00:03 UTC, abejburton commented
@jgibson517 looks good, just submitted all my revisions so you can move ahead with that

2024-05-10 16:08 UTC, abejburton approved these changes

2024-05-10 17:06 UTC, merged